coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: null
        only_pulls: false
        branches: null
        flags: null
        paths: null
        message: "[SkYNewZ/rest-fornite-api] : "
  parsers:
    javascript:
      enable_partials: yes