version: '3'

services:
  api:
    image: skynewz/fortnite-api
    restart: always
    ports:
      - "3000:3000"
    depends_on: 
      - cache
      - database
    environment:
        # replace XXXXX by your values
      - LOGIN_EMAIL=XXXXX
      - LOGIN_PASSWORD=XXXXX
      - OAUTH_EPIC_LAUNCHER=XXXXX
      - OAUTH_FORTNITE=XXXXX
      - DATABSE_CONNECTION_STING=postgres://postgres:secretpassword@database:5432/fortnite-api

  database:
     image: postgres
    # you should stay comment this line for prevent useless open port on your server
    #  ports:
    #    - 5432:5432
     environment:
       - POSTGRES_PASSWORD=secretpassword
       - POSTGRES_DB=fortnite-api
     volumes:
        # if you want to persist data
       - ./postgres:/var/lib/postgresql/data